title: A brand new course for you to learn
tagline: Learn how to make courses on the course maker using a course
description: Here you might use some MD probably
template:
  name: ''
  repo: undefined-template
before:
  - body: hello-world.md
    title: Hello
    type: createIssue
